# specify which database and adapter to use for which environment

development:
  adapter: sqlite3 
  database: to-do-app-development

test:
  adapter: sqlite3 
  database: to-do-app-test

production:
  adapter: sqlite3 
  database: to-do-app-production
